name: run-script
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  cebolla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python script.py -i cebolla_caramelizada
  pepino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python script.py -i pepino
